name: Generic Discord Workflow Notification
description: Sends detailed Discord notifications for GitHub Actions workflow changes
branding:
  icon: 'bell'
  color: 'blue'

inputs:
  discord_webhook_url:
    description: 'Discord webhook URL'
    required: true
  needs_json:
    description: 'Needs JSON'
    required: true
  wake_up_log:
    description: 'Wake up log output'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send Discord Notification
      shell: bash
      env:
        DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}
        WORKFLOW_NAME: ${{ github.workflow }}
        REPO_NAME: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        RUN_ID: ${{ github.run_id }}
        COMMIT_SHA: ${{ github.sha }}
        NEEDS_JSON: ${{ inputs.needs_json }}
        WAKE_UP_LOG: ${{ inputs.wake_up_log }}
      run: |
        RUN_URL="https://github.com/$REPO_NAME/actions/runs/$RUN_ID"
        COMMIT_URL="https://github.com/$REPO_NAME/commit/$COMMIT_SHA"

        # Determine color based on job failures
        total_failed=$(echo "$NEEDS_JSON" | jq '[.[] | select(.result == "failure")] | length')
        if [ "$total_failed" -gt 0 ]; then
          COLOR=15158332  # red
          STATUS_EMOJI="❌"
        else
          COLOR=3066993   # green
          STATUS_EMOJI="✅"
        fi

        # Prepare job list with emojis
        job_summaries=$(echo "$NEEDS_JSON" | jq -r '. | to_entries[] | if .value.result == "success" then "✅ \(.key)" else "❌ \(.key)" end')

        # Create main description
        description="**Repository:** $REPO_NAME\n**Branch:** \`$BRANCH\`\n\n**Job Results:**\n$job_summaries"

        # If wake_up_log exists, add it prominently
        if [ -n "$WAKE_UP_LOG" ]; then
          description="$description\n\n**🚀 App Wake-Up Status:**\n> $WAKE_UP_LOG"
        fi

        # Build the Discord JSON payload
        payload=$(jq -n \
          --arg workflow_name "$WORKFLOW_NAME" \
          --arg description "$description" \
          --arg run_url "$RUN_URL" \
          --arg commit_sha "${COMMIT_SHA:0:7}" \
          --arg commit_url "$COMMIT_URL" \
          --argjson color "$COLOR" \
          --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
          '{
            embeds: [{
              title: ("Workflow Run " + $workflow_name),
              description: $description,
              color: $color,
              fields: [
                {
                  name: "Workflow Run",
                  value: "[View Run](\($run_url))",
                  inline: true
                },
                {
                  name: "Commit",
                  value: "[\($commit_sha)](\($commit_url))",
                  inline: true
                }
              ],
              footer: {
                text: ("Workflow Completed • " + $workflow_name)
              },
              timestamp: $timestamp
            }]
          }')

        # Send the message to Discord
        curl -H "Content-Type: application/json" \
             -d "$payload" \
             "$DISCORD_WEBHOOK_URL"
