name: Generic Discord Workflow Notification
description: Sends detailed Discord notifications for GitHub Actions workflow changes
branding:
  icon: 'bell'
  color: 'blue'

inputs:
  discord_webhook_url:
    description: 'Discord webhook URL'
    required: true
  needs_json:
    description: 'Needs JSON containing job results'
    required: true
  wake_up_log:
    description: 'Wake-up log output if available'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send Discord Notification
      shell: bash
      env:
        DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}
        WORKFLOW_NAME: ${{ github.workflow }}
        REPO_NAME: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        RUN_ID: ${{ github.run_id }}
        COMMIT_SHA: ${{ github.sha }}
        NEEDS_JSON: ${{ inputs.needs_json }}
        WAKE_UP_LOG: ${{ inputs.wake_up_log }}
      run: |
        echo "DEBUG - Wake Up Log: $WAKE_UP_LOG"
        
        RUN_URL="https://github.com/$REPO_NAME/actions/runs/$RUN_ID"
        COMMIT_URL="https://github.com/$REPO_NAME/commit/$COMMIT_SHA"
        
        # Default to green color
        COLOR=3066993

        # Build description text cleanly
        description_text="**Repository:** $REPO_NAME
        **Branch:** \`$BRANCH\`

        **Job Results:**"

        # Add job results
        for job_name in $(echo "$NEEDS_JSON" | jq -r 'keys[]'); do
          result=$(echo "$NEEDS_JSON" | jq -r --arg job "$job_name" '.[$job].result')
          if [ "$result" = "success" ]; then
            description_text="$description_text\n✅ $job_name"
          else
            description_text="$description_text\n❌ $job_name"
            COLOR=15158332  # Turn red if any job failed
          fi
        done

        # Add wake up log if present
        if [ -n "$WAKE_UP_LOG" ]; then
          description_text="$description_text\n\n**🚀 App Wake-Up Status:**\n> $WAKE_UP_LOG"
        fi

        # Build final payload
        payload=$(jq -n \
          --arg workflow_name "$WORKFLOW_NAME" \
          --arg description_text "$description_text" \
          --arg run_url "$RUN_URL" \
          --arg commit_sha "${COMMIT_SHA:0:7}" \
          --arg commit_url "$COMMIT_URL" \
          --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
          --argjson color "$COLOR" \
          '{
            embeds: [{
              title: ("Workflow Run " + $workflow_name),
              description: $description_text,
              color: $color,
              fields: [
                {
                  name: "Workflow Run",
                  value: "[View Run](\($run_url))",
                  inline: true
                },
                {
                  name: "Commit",
                  value: "[\($commit_sha)](\($commit_url))",
                  inline: true
                }
              ],
              footer: {
                text: ("Workflow Completed • " + $workflow_name)
              },
              timestamp: $timestamp
            }]
          }')

        # Send Discord notification
        curl -H "Content-Type: application/json" \
             -d "$payload" \
             "$DISCORD_WEBHOOK_URL"
